### 异步中的异常
- 非同步的代码在事件循环中执行的，无法通过try-catch捕获到。
- await这种Promise的同步写法，如果忽略了rejected状态的处理可以用try-catch来捕获。
- Promise的catch方法用于处理rejected状态而非处理异常。rejected状态未处理的话会触发Uncaught Rejection。可以通过如下方式进行统一的监听。
```
window.onunhandledrejection = (event) => {
  console.warn(`REJECTION: ${event.reason}`);
};
```